In [1]:
# class
class Student:
    def __init__(self,name):
        self.hello = '안녕하세요.'
        self.name = name
    def greeting(self):
        print(self.hello)
        print(self.name)

In [2]:
# stu_a, stu_b는 독립적인 인스턴스임, 속성임
stu_a = Student('gihun') # 클래스로부터 인스턴스 초기화
stu_b = Student('gana') # 클래스로부터 인스턴

In [3]:
stu_a.greeting()

안녕하세요.
gihun


## 클래스 속성

In [4]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age

In [5]:
p1 = Person('Ahri',312)
p2 = Person('David',18)

In [6]:
p1.__dict__

{'name': 'Ahri', 'age': 312}

In [7]:
p2.__dict__

{'name': 'David', 'age': 18}

In [8]:
class Person2:
    def __init__(self,name,age,address):
        self.hello = '안녕하세요.'
        self.name= name
        self.age= age
        self.address= address
        
    def greeting(self):
        print(f'{self.hello} 제 이름은 {self.name}입니다.')

In [9]:
Maria=Person2('Maria',23,'서울시 마포구')
Maria.greeting()

안녕하세요. 제 이름은 Maria입니다.


In [10]:
class Person3:
    def __init__(self,count):
        self.name = input('이름은 무엇인가요?')
        self.age = int(input('나이는 무엇인가요?'))
        self.address = input('주소는 무엇인가요?')
        self.count = count
    def introduce(self):
        print(f'{self.count} 이름: {self.name}\n{self.count} 나이:{self.age}\n{self.count} 주소: {self.address}')

In [11]:
maria = Person3('첫번째')
james = Person3('두번째')

이름은 무엇인가요? 마리아
나이는 무엇인가요? 20
주소는 무엇인가요? 서
이름은 무엇인가요? 제임스
나이는 무엇인가요? 21
주소는 무엇인가요? 유


In [12]:
maria.introduce()
james.introduce()

첫번째 이름: 마리아
첫번째 나이:20
첫번째 주소: 서
두번째 이름: 제임스
두번째 나이:21
두번째 주소: 유


### 비공개 속성 사용하기 __를 붙이면 비공개속성이 됨.

In [13]:
class Person2:
    def __init__(self,name,age,address,wallet):
        self.hello = '안녕하세요.'
        self.name= name
        self.age= age
        self.address= address
        self.__wallet = wallet # 비공개속성, 밖에서 접근 불가능하게 해놓음! 함수도 앞에 __붙이면 접근 불가능!
    def greeting(self):
        print(f'{self.hello} 제 이름은 {self.name}입니다.')
    def amount(self):
        print(self.__wallet)
    def pay(self, amount):
        if self.__wallet < amount:
            print('돈이 모자랍니다.')
            return
        self.__wallet -= amount

In [14]:
lks = Person2('이기수',88,'경기도 시흥',20000)

In [15]:
lks.amount()

20000


In [16]:
lks.pay(10000)

In [17]:
lks.amount()

10000


In [18]:
lks.pay(10001)

돈이 모자랍니다.


In [19]:
lks.amount()

10000


In [20]:
class Annie:
    def __init__(self):
        self.health,self.mp,self.AP=map(float,input('체력, 마나, AP를 입력하세요.').split())
    def amount(self):
        print(f'티버: 피해량 {self.AP*0.65+400}')

In [22]:
cha_1 = Annie()
cha_1.amount()

체력, 마나, AP를 입력하세요. 500 50 10


티버: 피해량 406.5


In [23]:
cha_2 = Annie()
cha_2.amount()

체력, 마나, AP를 입력하세요. 400 10 30


티버: 피해량 419.5


In [24]:
class Person2:
    org = 'Play data'
    def __init__(self,name,age,address,wallet):
        self.hello = '안녕하세요.'
        self.name= name
        self.age= age
        self.address= address
        self.__wallet = wallet # 비공개속성, 밖에서 접근 불가능하게 해놓음! 함수도 앞에 __붙이면 접근 불가능!
    def greeting(self):
        print(f'{self.hello} 제 이름은 {self.name}입니다.')
    def amount(self):
        print(self.__wallet)
    def pay(self, amount):
        if self.__wallet < amount:
            print('돈이 모자랍니다.')
            return
        self.__wallet -= amount
    @classmethod
    def from_string(cls,string):
        name, age, address, __wallet = string.split(',')
        return Person2(name,age,address,__wallet)

In [25]:
ygh = Person2('윤규헌',26,'경기도 광명',1000000)

In [26]:
ygh.org

'Play data'

In [27]:
lks.org

AttributeError: 'Person2' object has no attribute 'org'

In [28]:
Person2.org = 'Study data' # 클래스 자체의 속성을 의미함!

In [29]:
print(ygh.org)
print(lks.org)

Study data


AttributeError: 'Person2' object has no attribute 'org'

## 배열: 순서가 있는 같은 종류의 데이터가 저장되는 자료형(리스트보다 더 빠름)  
## 넘파이배열: 모든 요소가 같은 자료형이어야 하며, 요소의 개수는 바꿀 수 없다.  
## 리스트는 요소의 종류에 관계없이, 개수에 제한없이 삽입,삭제,수정 가능하므로 불연속적이다.

In [30]:
import numpy as np # axis = 0(인덱스), axis = 1(열)

In [31]:
a=np.array([_ for _ in range(10)])
a.shape

(10,)

In [33]:
!conda list

# packages in environment at C:\Users\Playdata\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.10                  py39_0  
anaconda-client           1.11.0           py39haa95532_0  
anaconda-navigator        2.3.1            py39haa95532_0  
anaconda-project          0.11.1           py39haa95532_0  
anyio                     3.5.0            py39haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.11.7           py39haa95532_0  
astropy                   5.1              py39h080aedc_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0 

In [32]:
ar = np.array([1.2, 2 ,5 ,7, 6.2]) # 표헌 범위가 더 큰 자료형으로 변환
ar

array([1.2, 2. , 5. , 7. , 6.2])

In [34]:
ar.dtype # float64bits, 8bites=1byte, 

dtype('float64')

## '?': boolean/'b': signed byte, /'B':unsigned byte/'i':int(i8)/'u':unsigned int/'f':float-f8(64bits)/'c':complex,c16(128bits)/'O':object/'U':Unicode string,U24  
## signed : 양수, 음수/ unsigned: 양수만

In [35]:
ar3 = np.array([_ for _ in range(3,10,3)], 'i8') # int 8bytes --> 8*8bit
ar3

array([3, 6, 9], dtype=int64)

In [36]:
ar4 = np.array([_ for _ in range(2, 10, 2)], 'f8')
ar4

array([2., 4., 6., 8.])

In [37]:
ar5 = np.array(['가나다라마' for _ in range(5)], 'U8') # <U8 은 Unicode로 최대 8글자!, 숫자는 생략해도 됨.
ar5

array(['가나다라마', '가나다라마', '가나다라마', '가나다라마', '가나다라마'], dtype='<U8')

In [38]:
ar6 = np.array(['가나다라마바사','가'])
ar6.dtype

dtype('<U7')

In [39]:
# np.inf = 무한대, np.nan = not a number

## 벡터화 연산: 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산을 지원함.

In [40]:
x = np.array([_ for _ in range(1,10)])
3**x

array([    3,     9,    27,    81,   243,   729,  2187,  6561, 19683],
      dtype=int32)

In [41]:
lis = [_ for _ in range(3)]
lis*3

[0, 1, 2, 0, 1, 2, 0, 1, 2]

In [42]:
a=np.array([1,2,3])
b=np.array([10,20,30])
2*a+b

array([12, 24, 36])

In [43]:
a == 2

array([False,  True, False])

In [44]:
b>10

array([False,  True,  True])

In [45]:
(a==2)&(b>10)
import pandas as pd

In [46]:
ar7 = np.array([[1,2,3],[4,5,6]])
ar7.shape

(2, 3)

In [47]:
ar8 = np.array([[10,20,30,40],[50,60,70,80]])
ar8

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열: axis=0 깊이, axis=1 행, axis=2 열/ shape(n1,n2,n3)  
## ndim: 차원/ shape: 배열의 크기

In [48]:
a = np.array([_ for _ in range(5)])
a

array([0, 1, 2, 3, 4])

In [49]:
a[2]

2

In [50]:
b = np.array([[1,2],[3,4]])
b[0,1]

2

In [51]:
b[1,:]

array([3, 4])

In [52]:
c = np.array([[0,1,2,3],[4,5,6,7]])
c[:,:2]

array([[0, 1],
       [4, 5]])

In [53]:
c=c.reshape(4,2)
c.ndim

2

In [54]:
m = np.array([_ for _ in range(0,15)]).reshape(3,5)
m1 = m[1,2]
m2 = m[2,-1]
m3 = m[1,1:3]
m4 = m[1:,2]
m5 = m[0:2,-2:]
print(m1)
print(m2)
print(m3)
print(m4)
print(m5)

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [55]:
d = np.zeros(3)
d

array([0., 0., 0.])

In [56]:
e = np.ones((2,3,4),'i')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [57]:
f = np.ones_like(e,'f')
f

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [58]:
g = np.arange(3, 12, 2)
g

array([ 3,  5,  7,  9, 11])

In [59]:
i = np.zeros([5],'U')
i

array(['', '', '', '', ''], dtype='<U1')

In [60]:
ex = np.linspace(0,100,20)
ex

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [62]:
f.T # 전치연산, 메소드가 아니라 속성이라는 점을 유의!

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)

In [63]:
ar9 = np.arange(12)
ar9.reshape(2,2,-1) # -1은 2,2하고 남은 차원으로 추정

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [64]:
ar9.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
ar9.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 배열 연결! hstack,vstack,dstack,stack,r_,c_,tile...

In [66]:
b1 = np.ones((2,3))
b2 = np.zeros((3,3))
print(b1)
print(b2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [67]:
np.vstack([b1,b2]) # 열이 같은 두 행렬을 합침

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
a1 = np.ones((2,3))
a2 = np.zeros((2,4))
print(a1)
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [69]:
np.hstack([a1,a2]) # 행이 같은 두 행렬을 합침

array([[1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]])

In [71]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))
print(c1)
print(c2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [82]:
np.dstack([c1,c2]) # 행이나 열이 아닌, 제 3의 축으로 합침 3x4,3x4 -> 3x4x2

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [74]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))
print(c1)
print(c2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [75]:
np.stack([c1,c2],axis=1)

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [81]:
np.stack([c1,c2],axis=0) #(2,3,4)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [90]:
np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [95]:
a = np.array([[0,1,2],[3,4,5]]) # 동잏한 배열을 반복하여 연결
np.tile(a,(2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [149]:
a = np.zeros((3,3))
#print(a)
b = np.ones((3,2))
#print(b)
a_b = np.hstack([a,b])
print(a_b)
c = np.arange(10,160,10)
#print(c)
c = c.reshape(3,5)
#print(c)
a_b_c = np.vstack([a_b,c])
print(a_b_c)
a_b_c = np.tile(a_b_c,(2,1))
a_b_c

[[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]
[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])