In [87]:
import numpy as np #numpy 쓸 생각을 한번도못함, 빈 리스트 조건은 not x !!

In [123]:
class Calculator:
    def __init__(self, value = 0): 
        self.value = value
        
    def add(self,*values): # 가변인자들은 튜플로 전달함. np.sum(x)와 sum(x)는 다름
        if not values:
            print('숫자를 입력해주세요.')
            return
        print(type(values))
        self.value = self.value + np.sum(values)
    def minus(self,*values):
        if not values:
            print('숫자를 입력해주세요.')
            return
        print(type(values))
        self.value = self.value - np.sum(values)
    def show_value(self):
        print(f'현재 값은 {self.value}입니다.')

In [124]:
c = Calculator()

In [125]:
c.add(100)

<class 'tuple'>


In [126]:
c.minus(20)

<class 'tuple'>


In [127]:
c.show_value()

현재 값은 80입니다.


In [128]:
c.add()

숫자를 입력해주세요.


In [129]:
c.minus([10,20])

<class 'tuple'>


In [130]:
c.add(range(1,6))

<class 'tuple'>


In [131]:
c.show_value()

현재 값은 65입니다.


In [137]:
# np.all(배열 a== 배열 b) : a와 b의 요소가 모두 같은지  

In [138]:
# 브로드캐스팅: 모양이 다른 배열 간의 연산이 가능하도록 크기를 변환시켜주는 것을 브로드캐스팅!
a= np.array([1,2,3])
b =np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [143]:
a=np.array([1,2,3,]) # 스칼라 2를 (2,2,2)로 확장해서 연산을 시켜줌
b=2
a*b
# 확장이 가능한 경우를 확인하는 규칙
# 1.numpy배열의 shape을 우측정렬하고 각 차원별로 숫자를 비교하고 비교하는 모든 차원이 두 조건 중 하나에 충족되어야 브로드캐스팅이 가능함.
# 1-1: 해당 차원 간의 숫자가 동일한 경우/ 1-2: 해당 차원 중 하나가 1인 경우 , 3x4x2와 4x1인 경우 우측 정렬 할시 44는 같지만 21이 다르긴하지만 1이 충족되므로 가능함

array([2, 4, 6])

In [152]:
a=np.arange(1,61).reshape(3,4,5) # 3x4x5와 4x1 result는 3x4x5가 됨.
b=np.array([[1],[3],[5],[7]])
a*b

array([[[  1,   2,   3,   4,   5],
        [ 18,  21,  24,  27,  30],
        [ 55,  60,  65,  70,  75],
        [112, 119, 126, 133, 140]],

       [[ 21,  22,  23,  24,  25],
        [ 78,  81,  84,  87,  90],
        [155, 160, 165, 170, 175],
        [252, 259, 266, 273, 280]],

       [[ 41,  42,  43,  44,  45],
        [138, 141, 144, 147, 150],
        [255, 260, 265, 270, 275],
        [392, 399, 406, 413, 420]]])

In [188]:
x = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(x)
print(x.min(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
45


### argmin(): 해당 배열의 제일 작은 값의 인덱스를 반환/  
### mean(),median, np.any(), np-all()

In [259]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])
print(practice.shape)
print(np.max(practice))
print(np.sum(practice,axis=0))                      ### numpy axis=0 ↓ ,, axis=1 ㅡ>
print(practice.max(axis=0))
print(practice.mean(axis=0))
print(practice.min(axis=0))

(5, 6)
9.0
[20.1 27.  23.6 26.  28.2 26.5]
[8.2 8.8 8.  9.  7.7 8.9]
[4.02 5.4  4.72 5.2  5.64 5.3 ]
[0.7 1.1 2.7 2.1 2.8 0.2]


In [239]:
import random
pra = iter(lambda: random.uniform(0,10),6.19)
next(pra)

7.617396186388506

In [262]:
practice.sort(axis=1)
practice

array([[1.1, 2.1, 6.5, 7.1, 7.2, 8. ],
       [2.7, 2.8, 3.3, 5.2, 7.7, 9. ],
       [0.7, 4.2, 4.3, 7.4, 8.8, 8.9],
       [0.2, 1.1, 2.9, 5.4, 6.9, 8.2],
       [2.7, 2.8, 3.1, 4.8, 7.4, 8.9]])

In [265]:
# argsort: 인덱스 정보를 가지고 와서 정렬된 인덱싱을 할 수 있음.
a= np.array([42,38,12,25])
j=np.argsort(a)
print(j)
j
print(a[j])

[2 3 1 0]
[12 25 38 42]


In [266]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [270]:
print(a[[0,1,2], [0,1,0]]) # 고급 인덱싱!!!!!!!!!!!!!!!!!!!
print(a[:,[0,1,0]])

[1 4 5]
[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [286]:
scores = np.array([[1,2,3,4],
                  [46,99,100,71],
                  [81,59,90,100]])
j = np.argsort(scores[1])
scores[:,j]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [287]:
# 분산: np.var()
# 표준편차: np.std()
# 중앙값: np.median()
# 최소값: np.percentile(x,0)
# 사분위수: np.precentile(x,25) 1분위수 ,, 50는 2분위수

### random과  np.random은 다른 것임!  
## 시드 설정하기: 컴퓨터 프로그램은 엄격한 무작위 수가 아니다. 정해진 알고리즘에 의해서 난수처럼 보이는 수열을 생성하므로 기준이 되는 시작 수를 시드라 함.  
## np.random.seed() -인수로는 0 혹은 큰 정수를 넣어준다. np.random.rand(5)인 경우 5개의 난수를 array에 넣어서 발생시켜줌 

In [290]:
np.random.seed(0)

In [291]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [292]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [293]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [294]:
np.random.seed(0)

In [295]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [296]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

### 데이터의 순서 바꾸기: shuffle함수를 사용함(in-place함수임)

In [297]:
x = np.arange(10)
print(x)
np.random.shuffle(x)
x

[0 1 2 3 4 5 6 7 8 9]


array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

### 데이터 샘플링: choice함수를 사용함(데이터의 집합에서 무작위로 한 개 선택)  
### np.random.choice(a,size=None,replace=True,p=None) **size**:정수,샘플,숫자/**replace**:boolean. True 중복 선택!/**p**:배열, 각 데이터가 선택될 확률

In [316]:
x = [_ for _ in range(1,6)]
np.random.choice(x,size=5,replace=False,p=[0.9,0.01,0.01,0.01,0.07])

array([1, 4, 5, 3, 2])

### rand: 0 ~ 1사이의 균일분포(shape)형태의 배열 생성/randn: 표준정규분포(shape)/randint:  균일분포의 정수 난수(low,high=None,size=None) high가 없으면 0~low, size는 난수의 개수

In [323]:
np.random.randint(0,45,6) # np.random은 high포함 x, random.randint는 포햠 O

array([23, 24,  4, 36, 44, 23])

In [335]:
np.random.seed(0)
k = np.random.randint(0,2,100)
#print(np.count_nonzero(k == 1)/100)
#print(list(k).count(1)/100)
print(np.sum(k)/100)

0.56
0.56
0.56


In [339]:
np.random.seed(0)
num_list = np.random.randint(1,7,100)
np.sum(num_list)/len(num_list)

3.42

### 정수 데이터 카운팅: unique명령이나 bincount명령으로 데이터 값을 분석할 수 있다. unique()는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력  
### return_counts인수를 True로 설정하면 각 값의 데이터 개수도 출력함.  
### 그러나 unique는 존재하는 데이터에 대해서만 세므로 bincount함수에 min/length 인수를 설정하여 쓰는 것이 더 편리하다. 0부터 minlength -1 까지의 숫자에 대해 각각 카운트를 합니다

In [341]:
print(np.bincount([1,1,2,2,2,3],minlength=6))
print(np.unique([1,1,2,2,2,3],return_counts=True))

[0 2 3 1 0 0]
(array([1, 2, 3]), array([2, 3, 1], dtype=int64))
