# 사이킷런 내장 데이터셋 연습 - iris data

In [176]:
from sklearn import datasets

In [177]:
# 사이킷런의 내장 데이터셋 리스트

In [178]:
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'data',
 'descr',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_cir

### 데이터 수집

In [179]:
#sklearn의 toy dataset import
from sklearn.datasets import load_iris
iris = load_iris()

### 데이터 탐색

In [181]:
# iris type 확인

In [182]:
type(iris) # 사이킷런의 번치라는 자료구조안에 있다.

sklearn.utils.Bunch

In [183]:
#데이터셋 설명
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [184]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [185]:
print(iris.DESCR)


.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [186]:
# 특성 데이터 확인 2차원 array
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [187]:
#특성의 이름 확인
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [188]:
# 타겟 데이터 확인
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [189]:
# 타겟(레이블, 클래스)의 이름 확인
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [190]:
# 레코드(샘플)의 수 확인
len(iris.data)

150

In [191]:
print(iris.filename)

iris.csv


In [192]:
# data 일부 확인
iris.data[0:5] # head안됨

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [193]:
#pandas DataFrame으로 데이터 확인
import pandas as pd
df_X = pd.DataFrame(data=iris.data, columns = iris.feature_names)
df_X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0              5.10000           3.50000            1.40000           0.20000
1              4.90000           3.00000            1.40000           0.20000
2              4.70000           3.20000            1.30000           0.20000
3              4.60000           3.10000            1.50000           0.20000
4              5.00000           3.60000            1.40000           0.20000
..                 ...               ...                ...               ...
145            6.70000           3.00000            5.20000           2.30000
146            6.30000           2.50000            5.00000           1.90000
147            6.50000           3.00000            5.20000           2.00000
148            6.20000           3.40000            5.40000           2.30000
149            5.90000           3.00000            5.10000           1.80000

[150 rows x 4 columns]

### 학습용/검증용 데이터 분리

In [194]:
# train set, test set으로 분리
#import sklearn.model_selection as ms
# train_test_split(arrays, test_size, random_state,shuffle) -> X_train, X_test, Y_train, Y_test = train_test_split(iris.data, test_size=0.3, random_state=42)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.3, random_state = 42) 

In [195]:
len(X_train)

105

### 모델 구축

In [197]:
# 1) 분석을 수행하기 위한 추정자(estimator) 생성
# 2) 학습 수행: 생성된 객체에 대해 fit() 메소드 수행
# 3) 예측 결과 도출: 생성된 객체 또는 학습이 수행된 분석 결과에 대해 predict()메소드 수행

In [198]:
from sklearn.tree import DecisionTreeClassifier
# 1) 분석을 수행하기 위한 추정자(estimator) 생성자
cls = DecisionTreeClassifier()
# 2) 학습 수행: 생성된 객체에 대해 fit() 메소드를 수행
cls.fit(X_train,y_train)
# 3) 예측 결과 수행
y_pred = cls.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

### 모델 평가

In [199]:
# 생성된 객체 또는 학습이 수행된 분석 결과에 대해 적합한 성능 평가 지표 도출
# from sklearn.metrics import ****
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

1.0

In [1]:
import pandas as pd
titanic_df = pd.read_csv('C:/Users/Playdata/Downloads/titanic_train.csv')
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
# survivied 열에서 생존자를 count
titanic_df.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [5]:
# 1등칸, 2등칸, 3등칸에 승선한 승객수는?
titanic_df.Pclass.value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

## DataFrame과 리스트,딕셔너리,넘파이 ndarray 상호변환
- 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기

In [6]:
import numpy as np

In [12]:
list1 = [1,2,3]
array1=np.array(list1)
# array1을 데이터프레임으로 변경하시오
col_name = ['col1']
df_1 = pd.DataFrame(array1, columns=col_name)
df_1

col1
0     1
1     2
2     3

- DataFrame을 넘파이,리스트,딕셔너리로 변환하기

In [13]:
list2=[[1,2,3]
      ,[11,22,33]]
col_name2=['col1','col2','col3']
df_2 = pd.DataFrame(list2, columns=col_name2)
df_2

col1  col2  col3
0     1     2     3
1    11    22    33

In [14]:
array2 = np.array(list2)
array2

array([[ 1,  2,  3],
       [11, 22, 33]])

- 딕셔너리를 데이터프레임으로 변환

In [16]:
dict1 = {'col1': [1,11],
        'col2':[2,22],
        'col3':[3,33]}
df_dict1 = pd.DataFrame(dict1)
df_dict1

col1  col2  col3
0     1     2     3
1    11    22    33

- 데이터프레임 -> ndarray로 변환

In [17]:
df_dict1.values

array([[ 1,  2,  3],
       [11, 22, 33]], dtype=int64)

- 데이터프레임 -> 리스트로 변환

In [18]:
df_dict1.values.tolist()

[[1, 2, 3], [11, 22, 33]]

- 데이터프레임 -> 딕셔너리로 변환

In [55]:
df_dict1.to_dict()

{'col1': {0: 1, 1: 11}, 'col2': {0: 2, 1: 22}, 'col3': {0: 3, 1: 33}}

In [47]:
# 1
titanic_df['Age_0'] = 0
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  
0        0         A/5 21171   7.2500   NaN        S      0  
1        0          PC 17599  71.2833   C85        C      0  
2        0  STON/O2. 3101282   7.9250   NaN        S      0  
3        0            113803  53.1000  C123        S      0  
4        0            373450   8.0500   NaN        S      0  
..     ...               ...      ...   ...      ...    ...  
886      0            211536  13.0000   NaN        S      0  
887      0            112053  30.0000   B42        S      0  
888      2        W./C. 6607  23.4500   NaN        S      0  
889      0            111369  30.0000  C148        C      0  
890      0            370376   7.7500   NaN        Q      0  

[891 rows x 13 columns]

In [48]:
# 2
titanic_df['Age_by_10'] = titanic_df.Age*10

In [49]:
#3 titanic_df에 'Family_No'열을 생성하고
titanic_df['Family_No'] = 0
titanic_df['Family_No'] = titanic_df.SibSp + titanic_df.Parch +1
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0        0         A/5 21171   7.2500   NaN        S      0      220.0   
1        0          PC 17599  71.2833   C85        C      0      380.0   
2        0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   
3        0            113803  53.1000  C123        S      0      350.0   
4        0            373450   8.0500   NaN        S      0      350.0   
..     ...               ...      ...   ...      ...    ...        ...   
886      0            211536  13.0000   NaN        S      0      270.0   
887      0            112053  30.0000   B42        S      0      190.0   
888      2        W./C. 6607  23.4500   NaN        S      0        NaN   
889      0            111369  30.0000  C148        C      0      260.0   
890      0            370376   7.7500   NaN        Q      0      320.0   

     Family_No  
0            2  
1            2  
2            1  
3            2  
4            1  
..         ...  
886          1  
887          1  
888          4  
889          1  
890          1  

[891 rows x 15 columns]

In [50]:
 #4 titanic_df에 Age_by_10열의 모든 데이터에 
titanic_df.columns
titanic_df['Age_by_10']=titanic_df.Age_by_10+10
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0        0         A/5 21171   7.2500   NaN        S      0      230.0   
1        0          PC 17599  71.2833   C85        C      0      390.0   
2        0  STON/O2. 3101282   7.9250   NaN        S      0      270.0   
3        0            113803  53.1000  C123        S      0      360.0   
4        0            373450   8.0500   NaN        S      0      360.0   
..     ...               ...      ...   ...      ...    ...        ...   
886      0            211536  13.0000   NaN        S      0      280.0   
887      0            112053  30.0000   B42        S      0      200.0   
888      2        W./C. 6607  23.4500   NaN        S      0        NaN   
889      0            111369  30.0000  C148        C      0      270.0   
890      0            370376   7.7500   NaN        Q      0      330.0   

     Family_No  
0            2  
1            2  
2            1  
3            2  
4            1  
..         ...  
886          1  
887          1  
888          4  
889          1  
890          1  

[891 rows x 15 columns]

In [51]:
# 5
titanic_df.drop('Age_0',axis=1,inplace=True)

In [52]:
# 6 titanic_df의 Age_by_10, Family_No열을 삭제하라
titanic_df.drop(['Age_by_10','Family_No'],axis=1,inplace=True)

In [53]:
# 7 titanic_df의 인덱스를 재설정하되, 기존의 인덱스는 컬럼을 추가하라
titanic_df.reset_index()

index  PassengerId  Survived  Pclass  \
0        0            1         0       3   
1        1            2         1       1   
2        2            3         1       3   
3        3            4         1       1   
4        4            5         0       3   
..     ...          ...       ...     ...   
886    886          887         0       2   
887    887          888         1       1   
888    888          889         0       3   
889    889          890         1       1   
890    890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 13 columns]

In [57]:
titanic_df.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

- 데이터 셀렉션 및 필터링

In [58]:
titanic_df.Pclass

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [59]:
titanic_df['Pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [60]:
# titanic_df에서 3등석 승객의 데이터만 조회하라

In [62]:
titanic_df.query('Pclass==3')

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
2              3         1       3                    Heikkinen, Miss. Laina   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
5      male   NaN      0      0            330877   8.4583   NaN        Q  
7      male   2.0      3      1            349909  21.0750   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
882  female  22.0      0      0              7552  10.5167   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[491 rows x 12 columns]

In [69]:
titanic_df[titanic_df['Pclass']==3]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
2              3         1       3                    Heikkinen, Miss. Laina   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
5      male   NaN      0      0            330877   8.4583   NaN        Q  
7      male   2.0      3      1            349909  21.0750   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
882  female  22.0      0      0              7552  10.5167   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[491 rows x 12 columns]

In [70]:
# 60세 이상인 승객 정보를 조회하라

In [71]:
titanic_df.query('Age>=60')

PassengerId  Survived  Pclass  \
33            34         0       2   
54            55         0       1   
96            97         0       1   
116          117         0       3   
170          171         0       1   
252          253         0       1   
275          276         1       1   
280          281         0       3   
326          327         0       3   
366          367         1       1   
438          439         0       1   
456          457         0       1   
483          484         1       3   
493          494         0       1   
545          546         0       1   
555          556         0       1   
570          571         1       2   
587          588         1       1   
625          626         0       1   
630          631         1       1   
672          673         0       2   
684          685         0       2   
694          695         0       1   
745          746         0       1   
829          830         1       1   
851          852         0       3   

                                                 Name     Sex   Age  SibSp  \
33                              Wheadon, Mr. Edward H    male  66.0      0   
54                     Ostby, Mr. Engelhart Cornelius    male  65.0      0   
96                          Goldschmidt, Mr. George B    male  71.0      0   
116                              Connors, Mr. Patrick    male  70.5      0   
170                         Van der hoef, Mr. Wyckoff    male  61.0      0   
252                         Stead, Mr. William Thomas    male  62.0      0   
275                 Andrews, Miss. Kornelia Theodosia  female  63.0      1   
280                                  Duane, Mr. Frank    male  65.0      0   
326                         Nysveen, Mr. Johan Hansen    male  61.0      0   
366  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  female  60.0      1   
438                                 Fortune, Mr. Mark    male  64.0      1   
456                         Millet, Mr. Francis Davis    male  65.0      0   
483                            Turkula, Mrs. (Hedwig)  female  63.0      0   
493                           Artagaveytia, Mr. Ramon    male  71.0      0   
545                      Nicholson, Mr. Arthur Ernest    male  64.0      0   
555                                Wright, Mr. George    male  62.0      0   
570                                Harris, Mr. George    male  62.0      0   
587                  Frolicher-Stehli, Mr. Maxmillian    male  60.0      1   
625                             Sutton, Mr. Frederick    male  61.0      0   
630              Barkworth, Mr. Algernon Henry Wilson    male  80.0      0   
672                       Mitchell, Mr. Henry Michael    male  70.0      0   
684                 Brown, Mr. Thomas William Solomon    male  60.0      1   
694                                   Weir, Col. John    male  60.0      0   
745                      Crosby, Capt. Edward Gifford    male  70.0      1   
829         Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0      0   
851                               Svensson, Mr. Johan    male  74.0      0   

     Parch       Ticket      Fare        Cabin Embarked  
33       0   C.A. 24579   10.5000          NaN        S  
54       1       113509   61.9792          B30        C  
96       0     PC 17754   34.6542           A5        C  
116      0       370369    7.7500          NaN        Q  
170      0       111240   33.5000          B19        S  
252      0       113514   26.5500          C87        S  
275      0        13502   77.9583           D7        S  
280      0       336439    7.7500          NaN        Q  
326      0       345364    6.2375          NaN        S  
366      0       110813   75.2500          D37        C  
438      4        19950  263.0000  C23 C25 C27        S  
456      0        13509   26.5500          E38        S  
483      0         4134    9.5875          NaN        S  
493      0     PC 17609   49.5042          NaN        C  
5

In [72]:
titanic_df[titanic_df.Age>=60]

PassengerId  Survived  Pclass  \
33            34         0       2   
54            55         0       1   
96            97         0       1   
116          117         0       3   
170          171         0       1   
252          253         0       1   
275          276         1       1   
280          281         0       3   
326          327         0       3   
366          367         1       1   
438          439         0       1   
456          457         0       1   
483          484         1       3   
493          494         0       1   
545          546         0       1   
555          556         0       1   
570          571         1       2   
587          588         1       1   
625          626         0       1   
630          631         1       1   
672          673         0       2   
684          685         0       2   
694          695         0       1   
745          746         0       1   
829          830         1       1   
851          852         0       3   

                                                 Name     Sex   Age  SibSp  \
33                              Wheadon, Mr. Edward H    male  66.0      0   
54                     Ostby, Mr. Engelhart Cornelius    male  65.0      0   
96                          Goldschmidt, Mr. George B    male  71.0      0   
116                              Connors, Mr. Patrick    male  70.5      0   
170                         Van der hoef, Mr. Wyckoff    male  61.0      0   
252                         Stead, Mr. William Thomas    male  62.0      0   
275                 Andrews, Miss. Kornelia Theodosia  female  63.0      1   
280                                  Duane, Mr. Frank    male  65.0      0   
326                         Nysveen, Mr. Johan Hansen    male  61.0      0   
366  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  female  60.0      1   
438                                 Fortune, Mr. Mark    male  64.0      1   
456                         Millet, Mr. Francis Davis    male  65.0      0   
483                            Turkula, Mrs. (Hedwig)  female  63.0      0   
493                           Artagaveytia, Mr. Ramon    male  71.0      0   
545                      Nicholson, Mr. Arthur Ernest    male  64.0      0   
555                                Wright, Mr. George    male  62.0      0   
570                                Harris, Mr. George    male  62.0      0   
587                  Frolicher-Stehli, Mr. Maxmillian    male  60.0      1   
625                             Sutton, Mr. Frederick    male  61.0      0   
630              Barkworth, Mr. Algernon Henry Wilson    male  80.0      0   
672                       Mitchell, Mr. Henry Michael    male  70.0      0   
684                 Brown, Mr. Thomas William Solomon    male  60.0      1   
694                                   Weir, Col. John    male  60.0      0   
745                      Crosby, Capt. Edward Gifford    male  70.0      1   
829         Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0      0   
851                               Svensson, Mr. Johan    male  74.0      0   

     Parch       Ticket      Fare        Cabin Embarked  
33       0   C.A. 24579   10.5000          NaN        S  
54       1       113509   61.9792          B30        C  
96       0     PC 17754   34.6542           A5        C  
116      0       370369    7.7500          NaN        Q  
170      0       111240   33.5000          B19        S  
252      0       113514   26.5500          C87        S  
275      0        13502   77.9583           D7        S  
280      0       336439    7.7500          NaN        Q  
326      0       345364    6.2375          NaN        S  
366      0       110813   75.2500          D37        C  
438      4        19950  263.0000  C23 C25 C27        S  
456      0        13509   26.5500          E38        S  
483      0         4134    9.5875          NaN        S  
493      0     PC 17609   49.5042          NaN        C  
5

In [73]:
titanic_df.loc[titanic_df.Age>=60,['Pclass']]

Pclass
33        2
54        1
96        1
116       3
170       1
252       1
275       1
280       3
326       3
366       1
438       1
456       1
483       3
493       1
545       1
555       1
570       2
587       1
625       1
630       1
672       2
684       2
694       1
745       1
829       1
851       3

In [76]:
titanic_df.iloc[0,8]

'A/5 21171'

In [77]:
titanic_df.loc[titanic_df.Ticket == 'A/5 21171']

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

In [79]:
# 60세가 넘는 승객의 이름과 나이를 조회하라
titanic_df.loc[titanic_df.Age>60,['Age','Name']]

Age                                       Name
33   66.0                      Wheadon, Mr. Edward H
54   65.0             Ostby, Mr. Engelhart Cornelius
96   71.0                  Goldschmidt, Mr. George B
116  70.5                       Connors, Mr. Patrick
170  61.0                  Van der hoef, Mr. Wyckoff
252  62.0                  Stead, Mr. William Thomas
275  63.0          Andrews, Miss. Kornelia Theodosia
280  65.0                           Duane, Mr. Frank
326  61.0                  Nysveen, Mr. Johan Hansen
438  64.0                          Fortune, Mr. Mark
456  65.0                  Millet, Mr. Francis Davis
483  63.0                     Turkula, Mrs. (Hedwig)
493  71.0                    Artagaveytia, Mr. Ramon
545  64.0               Nicholson, Mr. Arthur Ernest
555  62.0                         Wright, Mr. George
570  62.0                         Harris, Mr. George
625  61.0                      Sutton, Mr. Frederick
630  80.0       Barkworth, Mr. Algernon Henry Wilson
672  70.0                Mitchell, Mr. Henry Michael
745  70.0               Crosby, Capt. Edward Gifford
829  62.0  Stone, Mrs. George Nelson (Martha Evelyn)
851  74.0                        Svensson, Mr. Johan

In [93]:
# 60세가 넘고, 1등칸에 승선한 여성을 출력하라
titanic_df.loc[(titanic_df.Age>60)&(titanic_df.Pclass==1)&(titanic_df.Sex=='female')]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

In [103]:
fe ='female'
titanic_df.query('Sex == @fe')

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   
888          889         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
880      1            230433  26.0000   NaN        S  
882      0              7552  10.5167   NaN        S  
885      5            382652  29.1250   NaN        Q  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  

[314 rows x 12 columns]

### 정렬,Aggregation함수, GroupBy적용
- DataFrame,Series의 정렬 - sort_values()

In [98]:
titanic_df.sort_values(by=['Name'])

PassengerId  Survived  Pclass                                   Name  \
845          846         0       3                    Abbing, Mr. Anthony   
746          747         0       3            Abbott, Mr. Rossmore Edward   
279          280         1       3       Abbott, Mrs. Stanton (Rosa Hunt)   
308          309         0       2                    Abelson, Mr. Samuel   
874          875         1       2  Abelson, Mrs. Samuel (Hannah Wizosky)   
..           ...       ...     ...                                    ...   
286          287         1       3                de Mulder, Mr. Theodore   
282          283         0       3              de Pelsmaeker, Mr. Alfons   
361          362         0       2              del Carlo, Mr. Sebastiano   
153          154         0       3        van Billiard, Mr. Austin Blyler   
868          869         0       3            van Melkebeke, Mr. Philemon   

        Sex   Age  SibSp  Parch         Ticket     Fare Cabin Embarked  
845    male  42.0      0      0      C.A. 5547   7.5500   NaN        S  
746    male  16.0      1      1      C.A. 2673  20.2500   NaN        S  
279  female  35.0      1      1      C.A. 2673  20.2500   NaN        S  
308    male  30.0      1      0      P/PP 3381  24.0000   NaN        C  
874  female  28.0      1      0      P/PP 3381  24.0000   NaN        C  
..      ...   ...    ...    ...            ...      ...   ...      ...  
286    male  30.0      0      0         345774   9.5000   NaN        S  
282    male  16.0      0      0         345778   9.5000   NaN        S  
361    male  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C  
153    male  40.5      0      2       A/5. 851  14.5000   NaN        S  
868    male   NaN      0      0         345777   9.5000   NaN        S  

[891 rows x 12 columns]

In [99]:
titanic_df.sort_values(by=['Name','Pclass'])

PassengerId  Survived  Pclass                                   Name  \
845          846         0       3                    Abbing, Mr. Anthony   
746          747         0       3            Abbott, Mr. Rossmore Edward   
279          280         1       3       Abbott, Mrs. Stanton (Rosa Hunt)   
308          309         0       2                    Abelson, Mr. Samuel   
874          875         1       2  Abelson, Mrs. Samuel (Hannah Wizosky)   
..           ...       ...     ...                                    ...   
286          287         1       3                de Mulder, Mr. Theodore   
282          283         0       3              de Pelsmaeker, Mr. Alfons   
361          362         0       2              del Carlo, Mr. Sebastiano   
153          154         0       3        van Billiard, Mr. Austin Blyler   
868          869         0       3            van Melkebeke, Mr. Philemon   

        Sex   Age  SibSp  Parch         Ticket     Fare Cabin Embarked  
845    male  42.0      0      0      C.A. 5547   7.5500   NaN        S  
746    male  16.0      1      1      C.A. 2673  20.2500   NaN        S  
279  female  35.0      1      1      C.A. 2673  20.2500   NaN        S  
308    male  30.0      1      0      P/PP 3381  24.0000   NaN        C  
874  female  28.0      1      0      P/PP 3381  24.0000   NaN        C  
..      ...   ...    ...    ...            ...      ...   ...      ...  
286    male  30.0      0      0         345774   9.5000   NaN        S  
282    male  16.0      0      0         345778   9.5000   NaN        S  
361    male  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C  
153    male  40.5      0      2       A/5. 851  14.5000   NaN        S  
868    male   NaN      0      0         345777   9.5000   NaN        S  

[891 rows x 12 columns]

- Aggregation 함수 적용하기

In [104]:
titanic_df.groupby('Pclass').count() # titanic 데이터를 Pclass 별로 인덱스로 묶어서 그룹해줌

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               216       216   216  216  186    216    216     216   216   
2               184       184   184  184  173    184    184     184   184   
3               491       491   491  491  355    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         176       214  
2          16       184  
3          12       491

In [107]:
titanic_df.pivot_table(index='Pclass',aggfunc='count')

Age  Cabin  Embarked  Fare  Name  Parch  PassengerId  Sex  SibSp  \
Pclass                                                                     
1       186    176       214   216   216    216          216  216    216   
2       173     16       184   184   184    184          184  184    184   
3       355     12       491   491   491    491          491  491    491   

        Survived  Ticket  
Pclass                    
1            216     216  
2            184     184  
3            491     491

In [109]:
# 타이타닉의 선실 등급별로 총 승객수, 생존자 수를 조회하라 
titanic_df.groupby('Pclass')[['PassengerId','Survived']].agg({'PassengerId':'count','Survived':'sum'})

PassengerId  Survived
Pclass                       
1               216       136
2               184        87
3               491       119

In [110]:
# 위와 동일 경과 
titanic_df.pivot_table(index='Pclass',values=['PassengerId','Survived'],aggfunc={'PassengerId':'count','Survived':'sum'})

PassengerId  Survived
Pclass                       
1               216       136
2               184        87
3               491       119

### 결손 데이터 처리하기
- isna()로 결손 데이터 여부 확인

In [111]:
# 타이타닉 데이터 결측치 확인하기
# 방법 1) .info() 메소드

In [112]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
# 방법 2) isna() 활용하기

In [116]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [115]:
titanic_df[titanic_df.Cabin.isna()==False]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[204 rows x 12 columns]

- fillna()로 Missing 데이터 대체하기

In [117]:
# cabin열의 결측치를 모두 'C000'로 채우시오
titanic_df.Cabin.fillna('C000')

0      C000
1       C85
2      C000
3      C123
4      C000
       ... 
886    C000
887     B42
888    C000
889    C148
890    C000
Name: Cabin, Length: 891, dtype: object

In [119]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

### apply lambda 식으로 데이터 가공

In [120]:
def get_triple(x):
    return x*3

In [121]:
# get_triple을 람다함수로 작성하시오
(lambda x: x*3)

<function __main__.<lambda>(x)>

In [122]:
get_triple(3)

9

In [123]:
(lambda x: x*3)(3)

9

In [124]:
a=lambda x: x*3
a(3)

9

In [125]:
# lambda를 활용하여 타이타닉 데이터프레임의 Name의 글자수를 알려주는 Name_len열을 생성하시오.

In [129]:
#titanic_df.Name.values
titanic_df['Name_len'] = titanic_df.apply(lambda x: len(x.Name),axis=1)
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Name_len  
0        0         A/5 21171   7.2500   NaN        S        23  
1        0          PC 17599  71.2833   C85        C        51  
2        0  STON/O2. 3101282   7.9250   NaN        S        22  
3        0            113803  53.1000  C123        S        44  
4        0            373450   8.0500   NaN        S        24  
..     ...               ...      ...   ...      ...       ...  
886      0            211536  13.0000   NaN        S        21  
887      0            112053  30.0000   B42        S        28  
888      2        W./C. 6607  23.4500   NaN        S        40  
889      0            111369  30.0000  C148        C        21  
890      0            370376   7.7500   NaN        Q        19  

[891 rows x 13 columns]

In [130]:
# 타이타닉 성별의 데이터를 받아 'gender_person'열을 추가하라
titanic_df['gender_person']=titanic_df.apply(lambda x: 'male_person' if x.Sex == 'male' else 'female_person', axis=1)
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Name_len  gender_person  
0        0         A/5 21171   7.2500   NaN        S        23    male_person  
1        0          PC 17599  71.2833   C85        C        51  female_person  
2        0  STON/O2. 3101282   7.9250   NaN        S        22  female_person  
3        0            113803  53.1000  C123        S        44  female_person  
4        0            373450   8.0500   NaN        S        24    male_person  
..     ...               ...      ...   ...      ...       ...            ...  
886      0            211536  13.0000   NaN        S        21    male_person  
887      0            112053  30.0000   B42        S        28  female_person  
888      2        W./C. 6607  23.4500   NaN        S        40  female_person  
889      0            111369  30.0000  C148        C        21    male_person  
890      0            370376   7.7500   NaN        Q        19    male_person  

[891 rows x 14 columns]

In [131]:
# 타이타닉 age 18이상~22이하면 young, 아니면 Not young 
titanic_df['Age_category'] = titanic_df.apply(lambda x:'young' if (18<=x.Age<=22) else 'Not young',axis=1)
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Name_len  gender_person  \
0        0         A/5 21171   7.2500   NaN        S        23    male_person   
1        0          PC 17599  71.2833   C85        C        51  female_person   
2        0  STON/O2. 3101282   7.9250   NaN        S        22  female_person   
3        0            113803  53.1000  C123        S        44  female_person   
4        0            373450   8.0500   NaN        S        24    male_person   
..     ...               ...      ...   ...      ...       ...            ...   
886      0            211536  13.0000   NaN        S        21    male_person   
887      0            112053  30.0000   B42        S        28  female_person   
888      2        W./C. 6607  23.4500   NaN        S        40  female_person   
889      0            111369  30.0000  C148        C        21    male_person   
890      0            370376   7.7500   NaN        Q        19    male_person   

    Age_category  
0          young  
1      Not young  
2      Not young  
3      Not young  
4      Not young  
..           ...  
886    Not young  
887        young  
888    Not young  
889    Not young  
890    Not young  

[891 rows x 15 columns]

In [132]:
def get_age_cate(x):
    if x <= 5:
        cate = 'Baby'
    else:
        pass
    return cate
# 이런식으로 함수작성해서 apply(get_age_cate)넣어주면 됨

### 데이터 인코딩: 라벨 인코딩(카테고리 피처를 코드형 숫자값으로 변경

In [136]:
from sklearn.preprocessing import LabelEncoder
items = ['Tv','냉장고','전자렌지', '컴퓨터', '선풍기',' 선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(items)

LabelEncoder()

In [137]:
labels = encoder.transform(items)
labels

array([1, 2, 5, 6, 4, 0, 3, 3])

In [139]:
# 라벨 인코딩 규칙
encoder.classes_

array([' 선풍기', 'Tv', '냉장고', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

In [140]:
# 원본 값 확인
encoder.inverse_transform(labels)

array(['Tv', '냉장고', '전자렌지', '컴퓨터', '선풍기', ' 선풍기', '믹서', '믹서'], dtype='<U4')

- 원-핫 인코딩(One-Hot encoding)
- 해당 고유값만 1, 나머지는 0

In [157]:
# 먼저 라벨인코딩으로 변환 후 원핫인코딩
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import numpy as np
items = ['Tv','냉장고','전자렌지', '컴퓨터', '선풍기',' 선풍기', '믹서', '믹서']
# 라벨 인코딩
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
# 원,핫 인코딩으로 변환하기 전에 2차원 배열 구조로 변경
labels = labels.reshape((-1,1)) # 값이 저장되지는 않음 (2,-1)
# 원핫인코딩
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
oh_labels.toarray()

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

In [158]:
# 원본 값 확인
oh_encoder.inverse_transform(oh_labels)

array([[1],
       [2],
       [5],
       [6],
       [4],
       [0],
       [3],
       [3]])

In [164]:
# pandas를 활용한 원핫인코딩 만들기 - get_dummies()
import pandas as pd
df = pd.DataFrame({'items': ['Tv','냉장고','전자렌지', '컴퓨터', '선풍기',' 선풍기', '믹서', '믹서']})
df

items
0    Tv
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [165]:
result = pd.get_dummies(df)
result

items_ 선풍기  items_Tv  items_냉장고  items_믹서  items_선풍기  items_전자렌지  items_컴퓨터
0           0         1          0         0          0           0          0
1           0         0          1         0          0           0          0
2           0         0          0         0          0           1          0
3           0         0          0         0          0           0          1
4           0         0          0         0          1           0          0
5           1         0          0         0          0           0          0
6           0         0          0         1          0           0          0
7           0         0          0         1          0           0          0

In [166]:
result.values

array([[0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0]], dtype=uint8)

- 데이터 스케일링(피처 스케일링): 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업, 실제 특성값의 크기와 상관없이 동일한 조건으로 비교
- 표준화(standardization): 평균 0, 분산 1인 가우시안 정규 분포를 가진 값으로 변화 / x_new = (x-mean(x))/stdev(x)-표준편차
- 정규화(normalization): 서로 다른 피처의 크기를 통일하기 위해 변환(0~1)

In [167]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [169]:
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [172]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
np.set_printoptions(precision =6, suppress=True)
iris_scaled_df = pd.DataFrame(iris_scaled)
pd.options.display.float_format = '{:.5f}'.format
iris_scaled_df.describe()

0         1         2         3
count 150.00000 150.00000 150.00000 150.00000
mean   -0.00000  -0.00000  -0.00000  -0.00000
std     1.00335   1.00335   1.00335   1.00335
min    -1.87002  -2.43395  -1.56758  -1.44708
25%    -0.90068  -0.59237  -1.22655  -1.18381
50%    -0.05251  -0.13198   0.33648   0.13251
75%     0.67450   0.55861   0.76276   0.79067
max     2.49202   3.09078   1.78583   1.71210

- MinMaxScaler()

In [175]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(iris.data)
scaler.transform(iris.data)

array([[0.222222, 0.625   , 0.067797, 0.041667],
       [0.166667, 0.416667, 0.067797, 0.041667],
       [0.111111, 0.5     , 0.050847, 0.041667],
       [0.083333, 0.458333, 0.084746, 0.041667],
       [0.194444, 0.666667, 0.067797, 0.041667],
       [0.305556, 0.791667, 0.118644, 0.125   ],
       [0.083333, 0.583333, 0.067797, 0.083333],
       [0.194444, 0.583333, 0.084746, 0.041667],
       [0.027778, 0.375   , 0.067797, 0.041667],
       [0.166667, 0.458333, 0.084746, 0.      ],
       [0.305556, 0.708333, 0.084746, 0.041667],
       [0.138889, 0.583333, 0.101695, 0.041667],
       [0.138889, 0.416667, 0.067797, 0.      ],
       [0.      , 0.416667, 0.016949, 0.      ],
       [0.416667, 0.833333, 0.033898, 0.041667],
       [0.388889, 1.      , 0.084746, 0.125   ],
       [0.305556, 0.791667, 0.050847, 0.125   ],
       [0.222222, 0.625   , 0.067797, 0.083333],
       [0.388889, 0.75    , 0.118644, 0.083333],
       [0.222222, 0.75    , 0.084746, 0.083333],
       [0.305556, 0.

- fit() 데이터 변환을 위한 기준 정보 설정
- transform() 설정한 정보로 데이터를 변환
- fit_transform() fit과 transform을 한 번에 적용 및 수행
## 학습 데이터 세트와 테스트 데이터 세트에 fit(), transform() 적용 시 유의사항
- 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습, 데이터 세트로 분리
- 1항이 안되면 테스트 데이터 변환 시에 fit()이나 fit_transform()을 적용하지 않고 학습 데이터로 이미 fit()된 Scaler객체를 사용해 transform()으로 변환
- Scaler()객체를 이용해 학습 데이터 세트로 fit, transform으로 한 것에는 다시 fit하면 안됨. 바로 transform 해야 함